### ISSUE TITLE
Desktop-first columns using the `grid-column()` mixin

### ISSUE THREAD

**Issue by esr360** [alphagov/govuk_frontend_toolkit#232]
If using the `grid-column()` mixin, I can't see a way to create desktop-first columns. Whilst the `media()` mixin itself seems to have this option, when creating columns directly using the `grid-column()` mixin there is no such option. Consequently, these columns cannot work on IE8 without using respond.js. 

We have concluded that whilst we will support IE8, we have no need to provide them a responsive experience, and we are trying keep libraries/polyfills to a minimum so would like to avoid using respond.js. This means we must develop using desktop-fist principles, leaving any code in media queries to be for mobile devices only, with all desktop styles written outside of media queries.

I would be happy to submit a PR with this feature if it would get implemented.

Thanks,

**Comment by alextea** [comment]
Could you use the [IE helpers](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_conditionals.scss#L72) to set the styles for IE8 & below?

**Comment by edds** [comment]
The `grid-column` mixin makes use of the [`media` mixin](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/docs/mixins.md#conditionals) which will require you to create IE specific stylesheets to give IE columns. You can read more about how the grid system supports old IE versions [on the GDS Tech blog](https://gdstechnology.blog.gov.uk/2014/10/16/responsive-grid-system-which-works-in-ie6/).

**Comment by esr360** [comment]
Really appreciate the fast replies guys. 

We are not looking to create separate stylesheets for old IE browsers, ideally we would have just one stylesheet for all browsers. This is the ONLY edge case we have for any old IE browsers, so at this point creating a separate stylesheet just for this would be more hassle than including respond.js I feel.

I think we are quite adamant about having just one stylesheet and not using respond.js, so it looks like either way we will have to modify the toolkit source files.

Once again I sincerely appreciate the lightning fast responses.

**Comment by edds** [comment]
@esr360 I would really have a look at how the IE specific stylesheets work. They don't require any extra effort beyond setting it up the first time and then it "just works" whenever you use the grid styles and each user will still only have to download 1 stylesheet appropriate for their browser.

**Comment by esr360** [comment]
For those interested this is the solution I came up with:

```scss
@mixin grid-column($width, $full-width: tablet, $float: left, $mobile-first: false) {
  
  @if $mobile-first {
    @include media($full-width){
      float: $float;
      width: percentage($width);
    }
  } @else {
    float: $float;
    width: percentage($width);
    @include media('mobile') {
      float: none;
      width: 100%;
    }
  }
  
  @include ie-lte(7){
    width: (($site-width + $gutter) * $width) - $gutter;
  }

  padding: 0 $gutter-half;
  @include box-sizing(border-box);
  
}
```
