### ISSUE TITLE
Current buttons solution seems unnecessarily WET

### ISSUE THREAD

**Issue by esr360** [alphagov/govuk_frontend_toolkit#330]
The current solution for creating buttons doesn't seem very efficient when it comes to keeping code DRY.

I'm aware that these days with gzip compression, such duplications are of little concern for many people, but take a look at the generated CSS for just 3 GDS buttons:

http://codepen.io/esr360/pen/BLWNEq?editors=1100#0

We're talking about 260 lines of CSS, or ~5kb worth, for 3 buttons.

There are much smarter ways to go about this. Would people be interested in a pull request addressing this issue? I would be happy to put one together. 

To give you an idea, the solution I'm currently using is essentially:

```scss
%action--core {
  display: inline-block;
  vertical-align: top;
  font-size: 1em;
  padding: 0.5em 0.75em;
  margin-right: 0.3em;
  text-decoration: none;
  text-rendering: optimizeLegibility;
  cursor: pointer;
  -webkit-font-smoothing: antialiased;
  -webkit-appearance: none;
  font-family: $font--primary;
  border-bottom: 2px solid;
  padding-bottom: 0.4em; // compensate for above border   
  line-height: 1.4;
  &:focus {
    outline: 3px solid $outline;
  }
  &.small {
    @extend %h6;
  }
  &.large {
    @extend %h4;
  }
}

@mixin action--core($background: $button-colour, $text-color: $white) {
  @extend %action--core;
  background-color: $background;
  color: $text-color;
  border-color: darken($background, 10%);
  &:hover {
    background-color: darken($background, 5%);
    color: $text-color;
  }
  &:active {
    color: $text-color;
  }
}
```

Which would be implemented like so:

```scss
.action {

  &--primary {
    @include action--core($button-colour);
  }

  &--secondary {
    @include action--core(
      $background: $grey-3, 
      $text-color: $text-colour
    );
  }

  &--delete {
    @include action--core($red);
  }

}
```

3 buttons now becomes just 2kb and 81 lines of code.

I would be interested in everyone's thoughts on this.
