### ISSUE TITLE
External link icons not being generated

### ISSUE THREAD

**Issue by alexmuller** [alphagov/govuk_frontend_toolkit#95]
We have some `image-url` attributes that are used for the external link icon. I can't make these work.

I don't know enough about how Compass and Sass work together, but Compass appears to be a Ruby gem. We're using the frontend toolkit in a Node.js project.

From https://assets.performance.service.gov.uk/spotlight/stylesheets/spotlight.css:

``` css
a[rel="external"]:after {
  background-image: image-url(external-link.png);
  background-repeat: no-repeat;
  content: "\A0\A0\A0\A0\A0";
  background-position: right 3px;
}
```
